# Generated by Django 2.2.1 on 2019-06-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, verbose_name='user_id')),
                ('twitter_handle', models.CharField(max_length=40, verbose_name='twitter_handle')),
            ],
        ),
        migrations.CreateModel(
            name='tweets_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=40, verbose_name='twitter_handle')),
                ('tweet_id', models.BigIntegerField(verbose_name='tweets_id')),
                ('tweet_data', models.CharField(max_length=280, verbose_name='tweet_data')),
                ('tweet_date', models.DateField(verbose_name='date')),
            ],
        ),
    ]
