# Generated by Django 2.2.1 on 2019-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets_data',
            fields=[
                ('twitter_handle', models.CharField(max_length=40, verbose_name='twitter_handle')),
                ('tweet_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='tweets_id')),
                ('tweet_data', models.TextField(max_length=1000, verbose_name='tweet_data')),
                ('tweet_date', models.DateField(verbose_name='date')),
                ('class_label', models.IntegerField(default=-1, verbose_name='class_label')),
            ],
        ),
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, verbose_name='user_id')),
                ('twitter_handle', models.CharField(default='abc@abc.com', max_length=40, verbose_name='twitter_handle')),
                ('friend_Email', models.CharField(max_length=40, verbose_name='friend_Email')),
                ('url', models.CharField(default='', max_length=100, verbose_name='url')),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('user_id', 'twitter_handle')},
            },
        ),
    ]
