# Generated by Django 2.2.1 on 2019-06-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets_data',
            name='class_label',
            field=models.IntegerField(default=-1, verbose_name='class_label'),
        ),
    ]
