# Generated by Django 2.2.1 on 2019-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_data',
            name='tweet_data',
            field=models.TextField(max_length=280, verbose_name='tweet_data'),
        ),
    ]
