# Generated by Django 2.2.1 on 2019-07-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_data',
            name='tweet_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
