# Generated by Django 2.2.1 on 2019-06-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190617_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweets_data',
            name='tweet_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='tweets_id'),
        ),
    ]
