# Generated by Django 2.2.1 on 2019-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190712_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_data',
            name='tweet_date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
