# Generated by Django 2.2.1 on 2019-07-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190712_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets_data',
            name='class_label',
        ),
        migrations.AddField(
            model_name='tweets_data',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='counter'),
        ),
        migrations.AddField(
            model_name='tweets_data',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
        migrations.AddField(
            model_name='tweets_data',
            name='sum_score',
            field=models.IntegerField(default=0, verbose_name='sum_score'),
        ),
    ]
