# Generated by Django 2.2.1 on 2019-06-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190617_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='following',
            name='friend_Email',
            field=models.CharField(default='abc@abc.com', max_length=40, verbose_name='friend_Email'),
        ),
        migrations.AddField(
            model_name='following',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='following',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='url'),
        ),
    ]
