# Generated by Django 2.2.1 on 2019-06-18 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190618_2224'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('user_id', 'friend_Email')},
        ),
    ]
