# Generated by Django 2.2.1 on 2019-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190715_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_data',
            name='score',
            field=models.FloatField(default=0, verbose_name='score'),
        ),
    ]
