# Generated by Django 2.2.1 on 2019-07-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190715_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets_data',
            name='tweet_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
