# Generated by Django 2.2.1 on 2019-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190727_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=40, verbose_name='twitter_handle')),
                ('tweet_data', models.TextField(max_length=1000, verbose_name='tweet_data')),
                ('noti_date', models.DateTimeField(verbose_name='noti_date')),
            ],
        ),
    ]
