# Generated by Django 2.2.1 on 2019-07-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets_data',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
