# Generated by Django 2.2.1 on 2019-07-04 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.User_detail')),
                ('FirstName', models.CharField(max_length=20, verbose_name='First_Name')),
                ('LastName', models.CharField(max_length=20, verbose_name='Last_Name')),
                ('dateOfBirth', models.DateField(verbose_name='DateOfBirth')),
            ],
        ),
    ]
