# Generated by Django 2.2.1 on 2019-06-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
    ]
