# Generated by Django 2.2.1 on 2019-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=300, verbose_name='Password'),
        ),
    ]
