# Generated by Django 2.2.1 on 2019-07-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='email',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
