# Generated by Django 2.2.1 on 2019-08-15 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='last_login'),
        ),
    ]
