# Generated by Django 2.2.1 on 2019-06-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190607_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_details',
        ),
    ]
