# Generated by Django 2.2.1 on 2019-07-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190716_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='email',
            field=models.CharField(max_length=60, null=True, verbose_name='email'),
        ),
    ]
