# Generated by Django 2.2.1 on 2019-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_user_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='User_detail',
        ),
    ]
