# Generated by Django 2.2.1 on 2019-06-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20190607_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
