# Generated by Django 2.2.1 on 2019-06-10 11:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_registration_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='lastName',
            new_name='FirstName',
        ),
        migrations.AddField(
            model_name='registration',
            name='LastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Last_Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User_detail'),
        ),
    ]
