# Generated by Django 2.2.1 on 2019-06-10 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20190610_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='User_detail',
        ),
    ]
