# Generated by Django 2.2.1 on 2019-06-10 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0010_auto_20190610_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Username')),
                ('password', models.CharField(max_length=300, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20, verbose_name='Last_Name')),
                ('LastName', models.CharField(max_length=20, verbose_name='Last_Name')),
                ('dateOfBirth', models.DateField(verbose_name='DateOfBirth')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User_detail')),
            ],
        ),
    ]
