# Generated by Django 2.2.1 on 2019-06-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190611_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='FirstName',
            field=models.CharField(max_length=20, verbose_name='First_Name'),
        ),
    ]
