# Generated by Django 2.2.1 on 2019-06-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20190617_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.User_detail'),
        ),
    ]
