# Generated by Django 2.2.1 on 2019-06-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20190618_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.User_detail'),
        ),
    ]
