# Generated by Django 2.2.1 on 2019-06-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_auto_20190618_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.User_detail'),
        ),
    ]
