# Generated by Django 2.2.1 on 2019-06-18 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20190618_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='isActive',
        ),
    ]
